#!/bin/sh

#Get the list of the network interfaces of the machine without displaying any detail
#for these interfaces. Only the list of names.

ifconfig -a | sed 's/[ \t].*//;/^$/d' # For Linux
# ifconfig -l #For mac
