#!/bin/sh

# Explain how connect yourself as new user. (With graphic session and ssh session)
Graphical : Put your login and password when asked
SSH : ssh <username>@<ip address or domain name> then put password when asked